owner: arkk4
repo: services.arkk4.com
user-agent: arkk4
sites:
  - name: zabbix.arkk4.com
    url: http://zabbix.arkk4.com
  - name: zabbix-01.arkk4.com
    url: http://zabbix-01.arkk4.com
  - name: zabbix-02.arkk4.com
    url: http://zabbix-02.arkk4.com
  - name: portainer.arkk4.com
    url: http://portainer.arkk4.com
  - name: blog.arkk4.com
    url: http://blog.arkk4.com
  - name: wiki.arkk4.com
    url: http://wiki.arkk4.com  
  - name: status.arkk4.com
    url: http://status.arkk4.com
#  - name: devbox-02.arkk4.online
#    url: http://devbox-02.arkk4.online
#  - name: devbox-03.arkk4.online
#    url: http://devbox-03.arkk4.online    
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Secret Site
#    url: $SECRET_SITE
#notifications:
#  - type: slack
#    channel: C016QTU9S9Y
#assignees:
#  - AnandChowdhary
status-website:
  cname: services.arkk4.com
  logoUrl: https://d338t8kmirgyke.cloudfront.net/icons/icon_pngs/000/008/123/original/monitoring-system.png
  name: Status
  introTitle: "статус внутренних сервисов"
  introMessage: services.arkk4.online
