owner: arkk4
repo: status.arkk4.online
user-agent: arkk4
sites:
  - name: devmap.arkk4.online
    url: http://devmap.arkk4.online
  - name: zabbix64.arkk4.online
    url: http://zabbix64.arkk4.online
  - name: zabbix-api.arkk4.online
    url: http://zabbix-api.arkk4.online
  - name: portainer.arkk4.online
    url: http://portainer.arkk4.online
  - name: ghost.arkk4.online
    url: http://ghost.arkk4.online
  - name: wiki.arkk4.online
    url: http://wiki.arkk4.online  
  - name: devbox-01.arkk4.online
    url: http://devbox-01.arkk4.online
  - name: devbox-02.arkk4.online
    url: http://devbox-02.arkk4.online
  - name: devbox-03.arkk4.online
    url: http://devbox-03.arkk4.online    
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Secret Site
#    url: $SECRET_SITE
#notifications:
#  - type: slack
#    channel: C016QTU9S9Y
#assignees:
#  - AnandChowdhary
status-website:
  cname: status.arkk4.online
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: Status
  introTitle: "**STATUS PAGE** статус внутренних сервисов и аптайм монитор by GitHub."
  introMessage: This is a sample status page which uses **real-time** data 
